This is makeindex, version 2.15 [TeX Live 2020] (kpathsea + Thai support).
Scanning style file ./thesis_RG.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file thesis_RG.acn....done (5 entries accepted, 0 rejected).
Sorting entries....done (11 comparisons).
Generating output file thesis_RG.acr....done (14 lines written, 0 warnings).
Output written in thesis_RG.acr.
Transcript written in thesis_RG.alg.
